# Generated by Django 3.2.9 on 2021-11-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubsystem', '0002_photo_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='notification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
