# Generated by Django 3.2.9 on 2021-11-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubsystem', '0005_auto_20211117_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description2',
            field=models.CharField(max_length=2000),
        ),
    ]
